### ISSUE TITLE
hackage release

### ISSUE THREAD

**Issue by christian-marie** [portnov/text-format-heavy#3]
I need this to compile with ghc > 8.2.2: https://github.com/portnov/text-format-heavy/commit/daa6799efe1b27aedf1cee37343b69a6b290fbbf

The latest hackage release does not have this patch, so I have to build from master. Please make a release.

**Comment by portnov** [comment]
Hello.

Uploading text-format-heavy-0.1.5.2.tar.gz... done!

**Comment by christian-marie** [comment]
Thanks!
